orbs:
  node: circleci/node@1.1.6

commands:
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1-all
          cache-key: package.json
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --ignore-scripts --no-progress

version: 2.1

jobs:
  tests_10:
    executor:
      name: node/default
      tag: '10'
    working_directory: ~/repo
    environment:
      - JEST_JUNIT_OUTPUT_DIR: './test-results/jest'
      - JEST_JUNIT_OUTPUT_NAME: 'results.xml'
    steps:
      - checkout
      - install_deps

      - run: yarn test:internal

      - store_test_results:
          path: test-results
  tests_12:
    executor:
      name: node/default
      tag: '12'
    working_directory: ~/repo
    environment:
      - JEST_JUNIT_OUTPUT_DIR: './test-results/jest'
      - JEST_JUNIT_OUTPUT_NAME: 'results.xml'
    steps:
      - checkout
      - install_deps

      - run: yarn test:internal

      - store_test_results:
          path: test-results

workflows:
  version: 2

  run_tests:
    jobs:
      - tests_10

      - tests_12
